### ISSUE TITLE
Disabling focus does not really work

### ISSUE THREAD

**Issue by ShrykeWindgrace** [chhackett/vty-windows#1] opened 2023-08-06 23:06 UTC
Strange behavior I spotted on the `vty-mode-demo`

Initially, there are no focus events at all. When I toggle them on, I start receiving them as VT sequences, which is kind of expected. However, when I then toggle them off, they still arrive, but as Windows Focus Event Records (`FocusEventRecordC`)! Further toggles do not change the situation, focus event keep coming.

Possible approaches:
- drop Windows Focus Event Records, expect only VT sequences events
- understand why the `\ESC[?1004l` sequence  can't disable all Focus Events for real - and why `\ESC[?1004h` enables too much. Possible Windows Terminal bug?
- something else?

It seems that the first option is the easiest in terms of efforts/gains ratio.

I am reluctant to implement it without a second opinion, because it could also be an issue with my terminal config somewhere.

**Comment by ShrykeWindgrace** [comment] 2023-08-06 23:08
If you want to test locally, the PR https://github.com/jtdaugherty/vty-crossplatform/pull/2 has the code.

**Comment by jtdaugherty** [comment] 2023-08-06 23:10
https://github.com/jtdaugherty/vty-crossplatform/pull/2 is now merged.

**Comment by chhackett** [comment] 2023-08-13 04:04
@ShrykeWindgrace 
Thanks for explaining the issue. I checked in a fix just implementing your option 1. I was unable to figure out how to toggle those focus events through the Windows API. But since the VT sequences work as designed, I just went with that.

I also did some cleanup:
- library no longer writes to hardcoded log files in C:\temp
- you can set an env var 'VTY_DEBUG_LOG' and input sequences and events will get logged there.

**Comment by ShrykeWindgrace** [comment] 2023-08-13 09:33
I'll test the changes shortly, thank you!

**Closed as completed** 2023-10-21 23:58 UTC
